### ISSUE TITLE
Load SNOMED Data into SQLite Database

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#11]
Analyze the SNOMED data and load relevant table(s) to the SQLite database

**Comment by noelgo** [comment]
Marc,

If you'd like, I could take on looking at and working on loading the SNOMED data into the SQLite database?  Unless you're "in rhythm" already from having done the prior data loads.

Also, did the WAR file sent to Amelia include any aspect that connects to your SQL Server on Arvixe?  Reason I ask is that if the SNOMED data will make the db file (and hence the WAR file) rather large, I wonder if we need to consider doing the lookups locally for all the other coding systems, but do remote lookup for SNOMED.

- Noel

**Comment by mooredynasty** [comment]
Yeah, it's probably easier for me to do SNOMED since I have the data and have SSIS configured.
Good idea about getting the SNOMED data via SQL Server.  I'm quite curious to see how much SNOMED will increase the SQLite database size.
The WAR file I sent her was just the build of the "Hello" app as it was checked into Github, so it will not prove all of our connectivity concerns.
Thanks,
Marc

Date: Sun, 22 Feb 2015 19:07:00 -0800
