### ISSUE TITLE
Meeting request : Seth: meeting request for server side dev setup

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#13]
Seth, Is 10 to 10:30 pm Wednesday  25th for Grails environment and some serverside tech discussion? If not, could you suggest another time? I'll create a hangout link and share after your confirmation.

Yesu

**Comment by sethanderson** [comment]
Sorry to answer so late. Yes, that's fine with me. Is that eastern timezone? @noelgo is part of the server side development too. @noelgo, does that time work for you?

**Comment by noelgo** [comment]
Hello, yes 10 pm EST this Wednesday 2/25 works for me.  Thanks!

**Comment by ypaulraj** [comment]
Yes 10pm EST.

hangout link: https://plus.google.com/hangouts/_/calendar/eWVzdWRhc0BnbWFpbC5jb20.8gd2mc6v2o623pa41j1h9r9ehk?authuser=0
