### ISSUE TITLE
Noel : Is the grails code under ATeamApp in working condition?

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#16]
Noel, I see you've checked in some sample code under ATeamApp  folder. Is this a grails project?  If yes, Can I just pull the code from this folder and create a project in GGTS and run as (run-app)?

Could you put the directions for running the application in this ticket?

**Comment by ypaulraj** [comment]
Noel, could you update this ticket when you get a chance?

**Comment by mooredynasty** [comment]
See my "6 AM thoughts" post on g+ for some info. This is a GGTS project that you can open and run.  I think Seth posted some instructions too





        Sent by Outlook for Android




On Thu, Feb 26, 2015 at 7:15 AM -0800, "ypaulraj" <notifications@github.com> wrote:
Noel, I see you've checked in some sample code under ATeamApp  folder. Is this a grails project?  If yes, Can I just pull the code from this folder and create a project in GGTS and run as (run-app)?

Could you put the directions for running the application in this ticket?

---
Reply to this email directly or view it on GitHub:
https://github.com/BryanCAlcorn/CS6440Project/issues/16

**Comment by mooredynasty** [comment]
In GGTS, I did File->Import, Grails->Grails Project, did NOT check "Copy resources into workspace" and Eclipse did the rest.  A note:  My Github repo maps to C:\Deve\CS6440\CS6440Project\ATeamApp locally and when opening GGTS I set my workspace to C:\Deve\CS6440\CS6440Project - it seems desirable to keep the Eclipse/GGTS folders like Servers, RemoteSystemsTempFiles, and .metadata out of the Github repo.

Date: Thu, 26 Feb 2015 18:30:54 -0800

**Comment by ypaulraj** [comment]
Thanks Marc. I'll try this.

**Comment by noelgo** [comment]
Sorry, late night at the office.

Assuming you're on Windows, when you get to https://github.com/BryanCAlcorn/CS6440Project , do the 
![image](https://cloud.githubusercontent.com/assets/3310128/6408725/f32a4170-be27-11e4-9bb5-5fa4df8525db.png)
Part of doing this should let you install the GitHub for Windows desktop app, as well as ask you where you want the repository to map to locally.

As in Marc's note, leave the "Copy resources into workspace" option unchecked when you import the project into GGTS.  This allows integration with GitHub to be retained (e.g. making and saving code changes generates a pending commit), whereas checking the option gives you a local copy of the project detached from the repository.

Other prerequisites are the steps Seth laid out in https://github.com/BryanCAlcorn/CS6440Project/wiki/Development-Environment , and then it's on to Run as > Grails Command (run-app), and hopefully seeing something like

![image](https://cloud.githubusercontent.com/assets/3310128/6408972/ff7e7556-be2a-11e4-8e92-8291ca108ac1.png)

If you get any errors, please post in case one of us has encountered the same thing, or if it's a different issue we can collaborate to resolve.

Thanks!

P.S. Marc's "6 am thoughts" post: https://plus.google.com/115860483541502229972/posts/g1cLdLmsSwQ
