### ISSUE TITLE
Please acknowledge this Issue request

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#2]
Hi All:

I am testing our github repo.  If you see this email,, Please open this issue in github and just type "ack." in the issue comment. This is important to make sure we have all members configured correctly. Thanks.

**Comment by sethanderson** [comment]
ack

**Comment by ypaulraj** [comment]
ack.

**Comment by BryanCAlcorn** [comment]
ack

**Comment by techfuzz** [comment]
ack

**Comment by noelgo** [comment]
ack

**Comment by noelgo** [comment]
My ack within github did not trigger e-mail alert like everyone else's did. Trying out this direct e-mail reply. 


----- Original Message -----

**Comment by ypaulraj** [comment]
Noel, I did receive a notification when you acked the ticket. The person who does the update does not receive an email. Other team members would receive an email.

noelgo <notifications@github.com>
Feb 14 (3 days ago)

to BryanCAlcorn/C., ypaulraj 
ack
