### ISSUE TITLE
create timeline UI 

### ISSUE THREAD

**Issue by sethanderson** [BryanCAlcorn/CS6440Project#22]

**Comment by mooredynasty** [comment]
What constitutes an event on the timeline? My first thought was that this is an Encounter record in FHIR. Can we confirm this?

**Comment by sethanderson** [comment]
I agree. We can add or subtract to that if need be later, but I think an encounter record in FHIR is a good event.

**Comment by BryanCAlcorn** [comment]
I agree as well.

**Comment by noelgo** [comment]
Sounds good.  We'll need to go with either Spark or HealthIntersections as the Gatech FHIR server does not support Encounter get calls.

**Comment by BryanCAlcorn** [comment]
Possible severities: Negligible, Minor, Moderate, Serious, Severe

<div class="table table-left">
	<section>
		<table class="data">
			<thead>
				<tr>
					<th scope=\"col\">Start</th>
					<th scope=\"col\">End</th>
					<th scope=\"col\">Event</th>
					<th scope=\"col\">Description</th>
					<th scope=\"col\">Link</th>
					<th scope=\"col\">Severity</th>
					<th scope=\"col\">Image</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>13 June 1985</td>
					<td>13 June 1985</td>
					<td>Blood Tests</td>
					<td>Some blood test information</td>
					<td></td>
					<td>Negligible</td>
				</tr>
			</tbody>
		</table>
	</section>
</div>

**Comment by BryanCAlcorn** [comment]
Data Format: https://docs.google.com/document/d/1ezQM_puwzFhn2Y2ESYNpvfwYEMuax-m9v_yXx6NiGh8/edit?usp=sharing
