### ISSUE TITLE
Create Final Presentation

### ISSUE THREAD

**Issue by techfuzz** [BryanCAlcorn/CS6440Project#26]
Final presentation is due April 24th. Only 1 person is required to do the narration.

Final presentation: https://docs.google.com/presentation/d/18sydXHEG7GJ1OJanC9aXwVs4Kj5d1j6NU-9xzCcIkQ8/edit?usp=sharing

Please contribute.

**Comment by mooredynasty** [comment]
Final presentation: https://docs.google.com/presentation/d/18sydXHEG7GJ1OJanC9aXwVs4Kj5d1j6NU-9xzCcIkQ8/edit?usp=sharing

Please contribute!

**Comment by techfuzz** [comment]
I had already started on the presentation, but I'll try to merge them together.

**Comment by mooredynasty** [comment]
OK, I've stopped editing mine

**Comment by techfuzz** [comment]
I've merged mine into yours and we'll use yours as the one we'll all work on together.  Editing can recommence.  Thanks.

**Comment by ypaulraj** [comment]
The screenshots really look good in the presentation.

**Comment by mooredynasty** [comment]
We have fairly good notes on most of the final presentation slides. Please wordsmith as needed.

What's still needed is feedback from our medical professionals.

**Comment by noelgo** [comment]
Posted first cut of video.  Received and incorporated feedback for how we might shorten the length.  Aiming to post second cut by Monday or Tuesday at the latest.  Will also be adding slide once feedback from test participants is in.

**Comment by noelgo** [comment]
Update on second cut:
https://plus.google.com/100103209947393828021/posts/NpDCDFor3UL

**Comment by noelgo** [comment]
Timeline and Adverse Drug Interactions screenshots updated.  Here are new links to the latest version:

Video
https://drive.google.com/file/d/0B_IBsMkjLl4bb3J1dXJzTy0zdHc/view?usp=sharing

PPT
https://docs.google.com/presentation/d/1mxTCw9aPM6JxZTGpuAD1U2AahcLOvGoaMT7e8QpX1Tg/edit?usp=sharing

If there is some flexibility on the time limit perhaps I could reduce the acceleration of the narration from 15% down to 10%.﻿

**Comment by noelgo** [comment]
We had another survey response come in today.  Here's an updated video with the User Evaluation slide added (look for it around the 4:10 mark).  Total length is 5:25.  I plan to submit to T-Square in a couple hours (around 10 pm EST).

https://drive.google.com/file/d/0B_IBsMkjLl4bTTZNcEVSOEdIcXM/view?usp=sharing

**Comment by noelgo** [comment]
Additional slide for User Evaluation was initially recorded at the office (little bit different acoustics).  Re-recorded the slide at home and here is the final version which has been submitted on T-Square.

https://drive.google.com/file/d/0B_IBsMkjLl4bMGFKUTNqQ0IzTUU/view?usp=sharing﻿

![final presentation video - submission confirmation](https://cloud.githubusercontent.com/assets/3310128/7331307/33178cde-ead8-11e4-8435-28c8f2574f43.PNG)
