### ISSUE TITLE
Convert timeline into .gsp

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#27]
Data format: https://docs.google.com/document/d/1ezQM_puwzFhn2Y2ESYNpvfwYEMuax-m9v_yXx6NiGh8/edit

**Comment by mooredynasty** [comment]
Work is in progress...

**Comment by mooredynasty** [comment]
A version of this is up and running. There's a bug such that the last Encounter's popup box doesn't display correctly.
