### ISSUE TITLE
Grails prototyping

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#3]
This ticket is for developing a small prototype in grails. All challenges or instructions for other members regarding setting up grails will be posted here.

**Comment by ypaulraj** [comment]
any update on this?

**Comment by mooredynasty** [comment]
I think Seth is going to work on this

**Comment by sethanderson** [comment]
I'll make time to get this finished tomorrow. 



—

**Comment by sethanderson** [comment]
Here's some documentation.
https://github.com/BryanCAlcorn/CS6440Project/wiki/Development-Environment

I'm about to check in the fresh grails project.
