### ISSUE TITLE
FHIR Wrapper - implement a Conditions query and mapper

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#30]
No work has been done on this.

Implement a Conditions query against FHIR and map the FHIR data to a DTO.  1-M with Patient.

**Comment by mooredynasty** [comment]
Query is done and mapper is partially implemented.  Need the 2nd half of the attributes implemented, tho.

**Comment by techfuzz** [comment]
Working on the second half of the attributes once I get the go-ahead from Noel.

**Comment by noelgo** [comment]
Sure Chris, much appreciated.

**Comment by techfuzz** [comment]
Condition mapper implemented
