### ISSUE TITLE
Encounter Mock Data - add additional attributes

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#31]
Most of the mock Encounter data needs some additional attributes.  Images would be helpful and it seems to be like these should be made part of the project and resulting WAR file

**Comment by techfuzz** [comment]
Can this be closed or do I need to create some more mock encounter data?

**Comment by mooredynasty** [comment]
In my mind the MockEncounterData class has enough "rows", but most of the Encounter records need Type, Hospitalization, and ImageUrl populated. A new property called Severity would not be amiss since it's used by the Timeline script.

**Comment by techfuzz** [comment]
I've added some of this information to the mock data.  Wasn't sure what values you were expecting so let me know if you want to see it differently.

**Comment by mooredynasty** [comment]
One of our sexy features is the image on the timeline, so it seems like we should have one for as many of the Encounters as possible
