### ISSUE TITLE
Open FDA Data - implement adverse interaction algorithm

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#34]
Implement an application tier service to analyze a patient's OtC and Prescription data and project adverse drug interactions.

**Comment by techfuzz** [comment]
The caution or warning symbol would be good to indicate an adverse reaction:
http://en.wikipedia.org/wiki/Hazard_symbol

**Comment by BryanCAlcorn** [comment]
Should the PrescriptionDTO and OTC DTO have an NdcProductDTO to identify them? Then we can query OpenFDA with them and check if there are any conflicts.

**Comment by mooredynasty** [comment]
Do we need more than the product code to query open FDA? Having an OpenFDADTO property on those classes to hold the results of the call sounds reasonable

**Comment by BryanCAlcorn** [comment]
Nope, we just need the 8 digit code (XXXX-XXXX). 
So  you're saying add an open fda object and an ndc object?

**Comment by mooredynasty** [comment]
I'm not sure we need an ndc object, but if it helps, I'd say go for it.

**Comment by BryanCAlcorn** [comment]
Ok, I'll play with it tomorrow
