### ISSUE TITLE
Open FDA Data - implement UI elements for adverse interactions

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#35]
Implement a dynamic UI element on the Patient Overview screen calling attention to a projected adverse drug interaction when applicable.

**Comment by techfuzz** [comment]
The caution or warning symbol would be good to indicate an adverse reaction:
http://en.wikipedia.org/wiki/Hazard_symbol

**Comment by techfuzz** [comment]
I implemented the UI elements for adverse reactions to the Prescriptions Tab.  Not sure how to best add something to the Patient Overview screen too.  Suggestions?

**Comment by BryanCAlcorn** [comment]
UI Elements should display on the patient overview without any clicks

**Comment by techfuzz** [comment]
I'm not sure how to add the adverse reaction notification to the patient overview.  Does anyone know how to do it?  It's currently displayed on the prescription details tab.

**Comment by sethanderson** [comment]
Do we want to just have a smaller alert that shows up right next to the word "Prescriptions"?

**Comment by mooredynasty** [comment]
That sounds good. Maybe with a mouse over explanation?

**Comment by sethanderson** [comment]
Yeah, that'll work well. I can figure that out. 



—

**Comment by BryanCAlcorn** [comment]
Yeah, each prescription will have the details of its interaction (thinking about it now, I may need to tweak it a bit). So maybe an indicator on the patient overview with generic details "this patient has prescriptions that have harmful interactions" or something. Then each prescription can have an icon with the first few characters of detail, when prescription is clicked full detail is displayed.

**Comment by BryanCAlcorn** [comment]
A prescription has an interaction if the text is not empty/null. Could put a convenience Boolean method on prescription dto

**Comment by BryanCAlcorn** [comment]
Oops, view model, not dto

**Comment by techfuzz** [comment]
I wrote the interaction to show/hide dynamically if it was not empty/null, but if you all think there is a better way to do that by all means go for it.
