### ISSUE TITLE
Update Style

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#37]
1. Remove Grails default banner
2. Possibly update default Bootstrap look & feel.

**Comment by sethanderson** [comment]
Working on this today. @BryanCAlcorn, I'll bug you for help if I get stuck, but I think I should be alright for now. I've done a little UI stuff in the past.

**Comment by techfuzz** [comment]
For the default banner, do we want call our application something along the lines of The A-EMR or A-EMR as a play on our team name?  Or something else?

E.g.
![a-emr](https://cloud.githubusercontent.com/assets/8484220/6996945/3afc10aa-db74-11e4-8e6e-d442580249f3.jpg)

**Comment by sethanderson** [comment]
haha, I like it. I'll put that in there

**Comment by techfuzz** [comment]
Other UI issues that were discussed in the meeting last night:
1. Expand the width of the timeline to 100% of the window
2. Fix the (X) button so it doesn't show up in other areas of the page

**Comment by sethanderson** [comment]
Fixed the timeline width and the close button and updated the styling of the app
