### ISSUE TITLE
Error running application  after pulling latest code

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#38]
I am unable to run the application after updating code. Could someone check if this is a problem only for me or everyone?

http://localhost:8080/ATeamApp/

............................
|Running Grails application
|Server running. Browse to http://localhost:8080/ATeamApp
....Error 
|
2015-04-02 22:42:12,091 [http-bio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - NoSuchMethodError occurred when processing request: [GET] /ATeamApp/
org.hl7.fhir.instance.formats.Parser.parseGeneral(Ljava/io/InputStream;)Lorg/hl7/fhir/instance/formats/ParserBase$ResourceOrFeed;. Stacktrace follows:
Message: Executing action [index] of controller [ateamapp.PatientListController]  caused exception: Runtime error executing action
    Line | Method
->>  198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker

**Comment by mooredynasty** [comment]
Hhmmm...  I'm afraid we've got the "It works on my machine" syndrome.
Can anyone else weigh in on this?

Date: Thu, 2 Apr 2015 19:44:14 -0700

**Comment by BryanCAlcorn** [comment]
The Build is green and the live application seem to be working.

**Comment by noelgo** [comment]
Yesu, see if you're using fhir-java-client-0.0.01-SNAPSHOT_0.0.82.2943.jar and fhir-0.0.82-Java-0.81.jar from the March 16th commit?

**Comment by BryanCAlcorn** [comment]
Looks like we're having a build issue. It's been running for 5 hours. Going to try and force stop.

**Comment by BryanCAlcorn** [comment]
It's a Web server issue. not a build issue!

**Comment by BryanCAlcorn** [comment]
Web server fixed, also added a timeout extension for Jenkins!

**Comment by techfuzz** [comment]
Per last night's meeting this issue is resolved.

**Comment by ypaulraj** [comment]
Yes, Its working now. Thanks.
