### ISSUE TITLE
Finalize the stories in the excel sheet

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#4]
Finalize the stories in the excel sheet. Also please add more details in the stores as reviewed in the last conf call. Thanks.

**Comment by BryanCAlcorn** [comment]
We should probably break the stories down into tasks and then create the tests in the issues list here. I'll add some Milestones and labels to the issue repo.

**Comment by techfuzz** [comment]
Stories were broken down into tasks.  Tests still need to be created here on Github.

**Comment by techfuzz** [comment]
Bryan created the test cases on the wiki - https://github.com/BryanCAlcorn/CS6440Project/wiki/Test-Cases

Issue resolved.
