### ISSUE TITLE
Implement Recommendations Tab on Patient Overview screen

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#40]
Show recommendations for the selected patient based on Gender and Age.  Beware of the unknown gender case.

**Comment by mooredynasty** [comment]
Recommendations are in Sqlite

**Comment by techfuzz** [comment]
When patient gender is unknown I suggest we show the recommendations based on the patient age only.

**Comment by mooredynasty** [comment]
Work-in-progress
