### ISSUE TITLE
Middleware : Meeting request for Wednesday 10:00pm

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#41]
Marc, Noel  : Can we have a meeting this 10:00 pm? Please suggest other time if this does not work fro you.

Thanks.

**Comment by mooredynasty** [comment]
I can give 30 minutes or so. What's the topic?

**Comment by noelgo** [comment]
Could we do Thursday evening instead?

**Comment by ypaulraj** [comment]
Marc, I had few questions on the data model. As Noel is available, I & Noel will chat on thursday evening. 

Noel, I'll send out the hangout link. Thanks.
