### ISSUE TITLE
junit tests

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#42]
I have few junit tests -- Is it ok to checkin under \ATeamApp\test\unit ?

**Comment by mooredynasty** [comment]
Fine by be, assuming they don't interfere with the build process.  @BryanCAlcorn, any thoughts on that?

**Comment by BryanCAlcorn** [comment]
Should be fine, I don't have any build steps in Jenkins currently to run unit tests.

If desired I can add that though, probably pretty easy to do.

**Comment by ypaulraj** [comment]
Thanks. We don't need to add the steps to autorun the unit tests yet. We can add it later if needed.
