### ISSUE TITLE
Create mock data for prescriptions

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#44]
This ticket is for creating mock data for prescriptions.

Note from Google Plus post.
Part of the issue is exercising the drug interactions UI elements, so it seems to me that we shouldn't just select drugs at random but deliberately configure scenarios we want.

**Comment by ypaulraj** [comment]
I'll create mock data in Java by randomly selecting few records from Chris spreadsheet.  Please update if you have any suggestions.

**Comment by mooredynasty** [comment]
We want to create some adverse interactions, but that requires some analysis. Also, it seems important to mix in the mock data with FHIR data  rather than just replacing it.

**Comment by ypaulraj** [comment]
Re Mixing mock data and FHIR data: I'll first implement the pure mock data from the excel sheet. Then the caller of the mock data can decide what attributes to get from mock and others from FHIR.

Re: adverse interactions -- I am not yet clear on this. If one of you can explain bit more, I can take a look at this.

**Comment by techfuzz** [comment]
@mooredynasty @BryanCAlcorn I downloaded the raw data files from the FDA that are used to update their OpenFDA database with the adverse drug events.  I am analyzing in an attempt to identify some pairs of medications to include in the mock data.

**Comment by mooredynasty** [comment]
@ypaulraj, right, so in the PatientManager class, the mock and FHIR data would be combined into the view model.

@BryanCAlcorn or @techfuzz  is probably better able to discuss adverse interactions, but what's needed is mock data that causes the openFDA web service code to say, "These two medicines (may) conflict".

**Comment by ypaulraj** [comment]
Thanks @mooredynasty  - -I'll take a look at it tonight.

**Comment by techfuzz** [comment]
@BryanCAlcorn https://docs.google.com/spreadsheets/d/1DebUipZ5DTRiOmuvK7V_GJSGHIC9PLj_TvZmcsLYFbU/edit?usp=sharing

**Comment by ypaulraj** [comment]
Created the basic mock data for prescriptions.

For  drug interactions : Should we keep a *List* of medicines which could potentially cause adverse reactions?
