### ISSUE TITLE
Recommendations tab is broken

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#45]
When clicked and AJAX 500 error is displayed.

**Comment by mooredynasty** [comment]
@BryanCAlcorn - not universally - got a patient ID to reproduce?

**Comment by mooredynasty** [comment]
Is this on the server?  Does the Sqlite database exist there?

**Comment by BryanCAlcorn** [comment]
Yes on the server. I thought the database was being built with the app into the war file?

**Comment by mooredynasty** [comment]
In Github it's zipped. I'd guess that's the issue

**Comment by BryanCAlcorn** [comment]
Hmm, ok, I'll have to check out the server then.

**Comment by BryanCAlcorn** [comment]
I unzipped the database on the server and refreshed (kept it in WEB-INF\db location), still getting the error with patient Chalmers, Peter James.
Is the .db file expected to be in a different location?

**Comment by mooredynasty** [comment]
The Production build asks for it at: ${catalina.base}/webapps/ATeamApp/WEB-INF/db/ATeam.db

Does Tomcat use the /webapps folder?  And this build is for the production environment, I suppose?

**Comment by BryanCAlcorn** [comment]
Yes and yes

**Comment by BryanCAlcorn** [comment]
ATeamApp is all lowercase in the production server though.

**Comment by noelgo** [comment]
Just tried a commit specifying lowercase 'ateamapp' in the dburl a couple minutes ago.  Still doesn't work.

ateam.databaseUrl = 'jdbc:sqlite:${catalina.base}/webapps/ateamapp/WEB-INF/db/ATeam.db'

**Comment by noelgo** [comment]
Another thing that will get fixed with the eventual resolution to this is how all patients are saying no data for the OTC Medicines tab, which shouldn't be the case since mockup data is rotated for everyone.

**Comment by noelgo** [comment]
jdbc and sqlite support a given on the Tomcat server?

**Comment by BryanCAlcorn** [comment]
I haven't installed anything for them yet. That could be the issue. When I asked I thought all we needed was tomcat.

**Comment by mooredynasty** [comment]
The Sqlite JAR should be included in the WAR file

**Comment by BryanCAlcorn** [comment]
Is the JAR exported with the WAR file? or does it need to be added separately?

**Comment by BryanCAlcorn** [comment]
The server has Java installed, not sure if we need anything special for JDBC.

**Comment by noelgo** [comment]
I think sqlite-jdbc-3.7.2.jar should make it into the WAR file since it's in /lib with all the other jars (jackson, fhir, etc).

**Comment by mooredynasty** [comment]
Is our AWS server Windows?

On Tomcat on my desktop, I get this error from Sqlite, presumedly because of the slashes not being backslashes:

java.sql.SQLException: path to 'C:\apache\apache-tomcat-8.0.17/webapps/ateamapp/
WEB-INF/db/ATeam.db': 'C:\apache\apache-tomcat-8.0.17\webapps\ateamapp' does not
 exist

**Comment by BryanCAlcorn** [comment]
The AWS server is linux, regular EC2 instance.

**Comment by mooredynasty** [comment]
Most likely there's a Tomcat log somewhere with the equivalent exception in it.

**Comment by BryanCAlcorn** [comment]
I'll check in a few

**Comment by BryanCAlcorn** [comment]
So, looks like for a while we were getting the File not found errors, but after Noel's fix and me unzipping the DB we're getting this:
2015-04-11 23:11:11,803 [http-nio-8080-exec-38] ERROR StackTrace  - Full Stack Trace:
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: Recommendation)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.throwex(DB.java:374)
        at org.sqlite.NestedDB.prepare(NestedDB.java:134)
        at org.sqlite.DB.prepare(DB.java:123)
        at org.sqlite.Stmt.executeQuery(Stmt.java:121)
        at databaseTier.Lookups.RecommendationData.getRecommendations(RecommendationData.java:59)
        at applicationTier.Patient.PatientManager.getRecommendationsTabModel(PatientManager.java:111)
        at ateamapp.PatientOverviewController.getRecommendationsData(PatientOverviewController.groovy:60)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by techfuzz** [comment]
Looks like it can't find the Recommendation table in the SQLite database.  Can you copy the db from your computer to the AWS server to see if that resolves the issue?

**Comment by BryanCAlcorn** [comment]
Looks like it's working with the latest build!

**Comment by noelgo** [comment]
Bryan, could you please check whether each new build clears out the unzipped db from WEB-INF/db?  Reason being github only has the zipped db.  I am getting the AJAX error on the Recommendations tab of the AWS app again.

**Comment by BryanCAlcorn** [comment]
Every time the application is deployed the db needs to be un zipped. I'm working on getting a script to run after each deployment, but running into permissions trouble. Going to try to get that worked out today if possible.

**Comment by BryanCAlcorn** [comment]
Jenkins now unzips the DB file after each deployment!
