### ISSUE TITLE
Latest Code Does Not Build in GGTS

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#47]
Description	Resource	Path	Location	Type
Project 'ATeamApp' is missing required source folder: '.link_to_grails_plugins/asset-pipeline-1.9.9/grails-app/conf'	ATeamApp		Build path	Build Path Problem

And 29 other similar errors.

**Comment by ypaulraj** [comment]
Is it in central build or your local eclipse build issue?

**Comment by ypaulraj** [comment]
sorry missed the headline --- It is in GGTS.. Let me pull the latest code and try to build now.

**Comment by BryanCAlcorn** [comment]
Jenkins build is green. 
One possibility is the classpath file might be messed up. Could try rolling it back.

**Comment by mooredynasty** [comment]
I think the solution is to right-click Project, Grails Tools, Refresh Dependencies.

http://stackoverflow.com/questions/10003881/missing-required-source-folder-link-to-grails-plugins-jquery-1-7-1-grails-app-i

**Comment by ypaulraj** [comment]
cool.

**Comment by mooredynasty** [comment]
Root cause is that .project has full paths in it, which vary for each of us.  Just something to be aware of
