### ISSUE TITLE
Update mock data rotation to support pure-alpha patient ids?

### ISSUE THREAD

**Issue by noelgo** [BryanCAlcorn/CS6440Project#49]
Currently when the patient id does not contain any numeric character, the rotation scheme isn't able to assign mock data scenarios for Encounters and OTC Medicines. (e.g. "f201" or "pat1" works but "xcda" or "ihe-pcd" won't)

**Comment by mooredynasty** [comment]
We could change that, but it was actually done that way on purpose:  No OTC meds or Encounters on file is a valid use case.

**Comment by noelgo** [comment]
Good point and agreed.  That does add to the data variation.
