### ISSUE TITLE
Create data for adverse drug interactions

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#52]
Chris created the data in https://docs.google.com/spreadsheets/d/1DebUipZ5DTRiOmuvK7V_GJSGHIC9PLj_TvZmcsLYFbU/edit?usp=sharing

**Comment by ypaulraj** [comment]
Should the data in the spreadsheet ( adverse drug interactions)  loaded into our database and consume it  OR should I just create mock data for this using the spreadsheet?

Basically I can create mock service and given the NDC code, it can supply a list of NDC codes which can cause adverse drug interactions using the spreadsheet. Please confirm.

**Comment by mooredynasty** [comment]
Looks to me like the Spark server deals in SNOMED for prescription drugs, not NDC.
