### ISSUE TITLE
Last item on timelines does not display

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#53]

**Comment by mooredynasty** [comment]
This should be fixed in the latest code.

**Comment by BryanCAlcorn** [comment]
It looks like that is fixed, but now the arrow buttons don't work. They move the pointer, but the correct information does not get displayed.

**Comment by BryanCAlcorn** [comment]
We can close this issue and open a new one, or if someone is going to take a look at it, we can leave this open.
