### ISSUE TITLE
Timeline data should be colored based on severity

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#54]
Possible values:
negligible
minor
moderate
serious
severe

**Comment by techfuzz** [comment]
Added the attribute to encounters and updated the mock data, but the color coding doesn't appear to be working yet.

**Comment by BryanCAlcorn** [comment]
Hmm, I'll take a look at the javascript for the timeline.

**Comment by BryanCAlcorn** [comment]
Found it, looks like the severity was left out of the HTML

**Comment by techfuzz** [comment]
We have quite the colorful display now.

**Comment by BryanCAlcorn** [comment]
Yes! Looks like a bunch of the encounter data is defaulting to Negligible, which is ok I guess.
