### ISSUE TITLE
Source Control Problem?

### ISSUE THREAD

**Issue by mooredynasty** [BryanCAlcorn/CS6440Project#55]
It looks to me like there could be a problem with some recent changes being lost in git.  Better check your recent work.  For instance, Yesu's "Merge branch 'master'" change from last night seems to have undone a few things, including Seth's UI fixes to the timeline and Noel's tweak to the database path in config.groovy.  Then not long after that, I made a similar commit.  Then I noticed Seth's changes were missing and tried to re-introduce them by hand, which was a silly thing to do.

Anyone good enough with git to untangle this?

@sethanderson @BryanCAlcorn @noelgo @ypaulraj @techfuzz

**Comment by mooredynasty** [comment]
I'll add that my commit "Fix #50" was a good one of a single file. I committed that locally, which put me ahead 1 commit and behind 5.  I had Github for Windows sync at that point, which created the "Fix #50' commit - good - and the 'Merge branch' commit - bad.  I think I should have pulled recent commits from master before syncing.

**Comment by BryanCAlcorn** [comment]
I had a similar problem. I just undid the changes that Git decided to make before re-checking in and syncing yesterday.

**Comment by mooredynasty** [comment]
In this case, I'm fairly sure that Yesu's 'Merge branch' and my Merge branch' commits should be burned out of the master branch.  Not quite 100% sure tho.  And then there's the question of how to do that...

**Comment by BryanCAlcorn** [comment]
It might be easiest to just go through and manually fix. It looks like a few things got jumbled together, so doing simple roll-backs might be more work...
We don't need to re-do the Groovy config, since I updated the path on the web server to have capital letters in it.

**Comment by noelgo** [comment]
Not a source control expert, but maybe this is where creating a new branch (is branching the same as forking?), working off of that, and merging it back later would warn about conflicts and provide options for how they should be handled?

**Comment by BryanCAlcorn** [comment]
You should get warnings about conflicts when checking into a single branch anyway, with the Git Windows client, it seems that it auto merges and doesn't really warn you.

**Comment by mooredynasty** [comment]
Branching works best with a designated VC person

**Comment by BryanCAlcorn** [comment]
Is this resolved?

**Comment by mooredynasty** [comment]
It is from my perspective
