### ISSUE TITLE
Search for "1" does not find any patients

### ISSUE THREAD

**Issue by techfuzz** [BryanCAlcorn/CS6440Project#58]
Not sure if this is by design or a bug.  If you type into the search field just the number 1 and click search it does not find any patients.  There are a coupe patients with the number 1 in their name.

Low priority bug.

**Comment by sethanderson** [comment]
It looks like it's only searching the beginning of the names and not anywhere in them. For example the search "ev" pulls up Eve and "ve" pulls up Vera but doesn't include Eve.

**Comment by techfuzz** [comment]
Ok, well this is more of a design decision with the way name searches are performed.  This really isn't a bug then so I'll close it.
