### ISSUE TITLE
What plugin is recommended for grails development in eclipse?

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#6]
I see a plugin named GGTS in eclipse marketplace. Is that the one recommended?

**Comment by mooredynasty** [comment]
I'd download the whole toolkit: http://spring.io/tools/ggts

--- Original Message ---

**Comment by sethanderson** [comment]
I think you should be able to use the GGTS plugin as well without issues.

https://github.com/BryanCAlcorn/CS6440Project/wiki/Development-Environment
