### ISSUE TITLE
Are the mock patient prescriptions merged with the fhir prescription data?

### ISSUE THREAD

**Issue by techfuzz** [BryanCAlcorn/CS6440Project#63]
All the issues for prescriptions have been closed, but it doesn't look like the mock data is showing up for any patients.  Was the code to do the merge completed or do we have a bug?

**Comment by mooredynasty** [comment]
Looks like the merge still needs to be done. I'll have a shot at it tonight.

**Comment by mooredynasty** [comment]
This seems to be working correctly.
