### ISSUE TITLE
Good luck everyone -- Pls post your linkedin profile if would like to stay connected.

### ISSUE THREAD

**Issue by ypaulraj** [BryanCAlcorn/CS6440Project#68]
Good luck in your next semester.

My linkedin profile.

https://www.linkedin.com/pub/yesudason-paulraj/1/a9a/60

**Comment by BryanCAlcorn** [comment]
Here's mine: https://www.linkedin.com/in/bryancalcorn

**Comment by ypaulraj** [comment]
@BryanCAlcorn  Thank you. Fixed it now.

**Comment by techfuzz** [comment]
www.linkedin.com/in/chrisruegsegger

**Comment by sethanderson** [comment]
https://www.linkedin.com/in/sethcanderson

**Comment by mooredynasty** [comment]
www.linkedin.com/in/mooredynasty 

Date: Fri, 24 Apr 2015 12:05:53 -0700

**Comment by noelgo** [comment]
noel.go@gatech.edu
noelvgo@gmail.com
(sorry, don't have a LinkedIn)
