### ISSUE TITLE
Timeline - When shifting left and right animation of events goes after the background timeline

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#69]
Not sure how this happened... needs to be fixed.

**Comment by BryanCAlcorn** [comment]
Same is happening with zoom-in and zoom-out

**Comment by techfuzz** [comment]
I'm not seeing that on my laptop, but I do see it on the AWS build.

**Comment by BryanCAlcorn** [comment]
That's weird... shouldn't be any different. Maybe I'll force a build and see what happens.

**Comment by BryanCAlcorn** [comment]
Still happening after the forced build. Doesn't seem like anything changed with it. If you're not seeing it locally then debugging will be difficult.

**Comment by techfuzz** [comment]
I think it may be a browser issue.  I see the problem when I use Chrome, but not IE when accessing the AWS build.

**Comment by BryanCAlcorn** [comment]
Interesting! Maybe we should just recommend using IE for now. Do you have Firefox? would be good to check there as well.

**Comment by mooredynasty** [comment]
Make sure to do a Control+F5 in the offending browser, just in case of a cached stylesheet

**Comment by BryanCAlcorn** [comment]
Still seeing it in Chrome after ctrl+f5

**Comment by techfuzz** [comment]
Don't have FF, but it's definitely a Chrome issue because I've reproduced it on two different computers that have Chrome on it.

**Comment by BryanCAlcorn** [comment]
Alright, I'll call it closed for now. I'll recommend using IE10 in the Test plan
