### ISSUE TITLE
Drug interactions are not displaying anymore

### ISSUE THREAD

**Issue by BryanCAlcorn** [BryanCAlcorn/CS6440Project#70]
For patient "Chalmers, Peter James" we used to have an interaction, it's not longer there...

**Comment by techfuzz** [comment]
When I search for Chalmers I'm getting multiple results back.  Selecting the one with Unknown DOB and Gender shows the adverse reactions.

**Comment by BryanCAlcorn** [comment]
Hmm, let me check again, I wasn't seeing them on the AWS build

**Comment by BryanCAlcorn** [comment]
Oh I see now. There are actually 2 copies of him without DoB. A while ago the lower one had the interactions, now it's the upper one (when searching for Chalmers). I'll update the test case accordingly.
